### ISSUE TITLE
关于学习方法的提问

### ISSUE THREAD

**Issue by wuse2003** [shuoshuof/17-openmv-#1]
你好！ 请问初学计算机视觉，上手opencv是个好的选择吗？opencv相关书籍有推荐吗？（我是看你智能车比赛，找资料，看到你的仓库，看你的csdn，发现你的研究方向和我很契合）

**Comment by shuoshuof** [comment]
可以先学opencv，熟悉图像处理的基本操作。然后写几个算法

**Comment by wuse2003** [comment]
好的，感谢！

**Comment by wuse2003** [comment]
最近准备把open art图像传给 tft屏幕。请问引脚连接是怎么分布呢![image](https://user-images.githubusercontent.com/94292942/222717449-9f60172b-0be5-4c6a-9353-3d52a853d83b.jpeg)

**Comment by shuoshuof** [comment]
这个屏幕没用过啊。我们一直都没有用过屏幕调试art
